version: "3.9"

networks:
  development:
  test:

volumes:
  gem_cache:
  shared_data:

services:
  app:
    build: .
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    stdin_open: true
    tty: true
    entrypoint: docker-entrypoint
    environment:
      APP_ENV: development

  test:
    image: mantra_app
    container_name: mantra_test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    stdin_open: true
    tty: true
    entrypoint: docker-entrypoint
    environment:
      APP_ENV: test
